import tkinter;

calculator = tkinter.Tk()

inputEntry = tkinter.Entry(calculator, bd=3).grid(row=6, columnspan=4)
percentButton = tkinter.Button(calculator, text="%").grid(row=0, column=0)
clearEButton = tkinter.Button(calculator, text="CE").grid(row=0, column=1)
clearButton = tkinter.Button(calculator, text="C").grid(row=0, column=2)
deleteButton = tkinter.Button(calculator, text="DEL").grid(row=0, column=3)
fractionButton = tkinter.Button(calculator, text="1/x").grid(row=1, column=0)
exponentButton = tkinter.Button(calculator, text="x^2").grid(row=1, column=1)
rootButton = tkinter.Button(calculator, text="root(x)").grid(row=1, column=2)
divideButton = tkinter.Button(calculator, text="/").grid(row=1, column=3)
sevenButton = tkinter.Button(calculator, text="7").grid(row=2, column=0)
eightButton = tkinter.Button(calculator, text="8").grid(row=2, column=1)
nineButton = tkinter.Button(calculator, text="9").grid(row=2, column=2)
multiplicationButton = tkinter.Button(calculator, text="x").grid(row=2, column=3)
fourButton = tkinter.Button(calculator, text="4").grid(row=3, column=0)
fiveButton = tkinter.Button(calculator, text="5").grid(row=3, column=1)
sixButton = tkinter.Button(calculator, text="6").grid(row=3, column=2)
minusButton = tkinter.Button(calculator, text="-").grid(row=3, column=3)
oneButton = tkinter.Button(calculator, text="1").grid(row=4, column=0)
twoButton = tkinter.Button(calculator, text="2").grid(row=4, column=1)
threeButton = tkinter.Button(calculator, text="3").grid(row=4, column=2)
plusButton = tkinter.Button(calculator, text="+").grid(row=4, column=3)
signButton = tkinter.Button(calculator, text="+/-").grid(row=5, column=0)
zeroButton = tkinter.Button(calculator, text="0").grid(row=5, column=1)
dotButton = tkinter.Button(calculator, text=".").grid(row=5, column=2)
equalButton = tkinter.Button(calculator, text="=").grid(row=5, column=3)

calculator.mainloop()